export default function Head() {
  return (
    <>
      <title>널리 이롭게 하라 - wantBe</title>
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </>
  );
}
